version: '3.8'

services: 
  mysql:
    image: mysql:8.0.0
    container_name: mysql8
    environment: 
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_TCP_PORT=3306
    volumes: 
      - datafiles:/var/lib/mysql
    restart: always

  website:
    container_name: php73
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=secret123
      #- MYSQL_DBNAME=
    ports: 
      - 8000:80
      - 8083:443
    depends_on: 
      - mysql
volumes: 
  datafiles: